"""Pharma Shipment Risk Analyzer - Streamlit web interface."""

import streamlit as st
import pandas as pd
import plotly.graph_objects as go
from pathlib import Path
import risk_logic


st.set_page_config(
    page_title="Pharma Shipment Risk Analyzer",
    layout="wide",
    initial_sidebar_state="collapsed"
)

st.title("Pharma Shipment Risk Analyzer")
st.markdown("Upload an Excel file to analyze cold-chain shipment risks and compliance.")


# File upload or use sample
uploaded_file = st.file_uploader("Upload shipment data (Excel file)", type=["xlsx"])

if uploaded_file is None:
    if st.button("📦 Load Sample Data"):
        sample_path = Path("sample_data/shipments_sample.xlsx")
        if sample_path.exists():
            uploaded_file = open(sample_path, "rb")
        else:
            st.error("Sample data file not found. Run `python3 scripts/generate_sample_data.py` first.")
            st.stop()
    else:
        st.info("Please upload an Excel file or click 'Load Sample Data' to begin.")
        st.stop()

# Read the file
try:
    df = pd.read_excel(uploaded_file)
except Exception as e:
    st.error(f"Error reading file: {e}")
    st.stop()

# Validate schema
is_valid, missing = risk_logic.validate_schema(df)
if not is_valid:
    st.error(f"Missing required columns: {', '.join(missing)}")
    st.stop()

# Add derived risk columns
df = risk_logic.add_risk_columns(df)

# KPI Row
col1, col2, col3, col4 = st.columns(4)

total_shipments = len(df)
high_risk_count = df["HighRisk"].sum()
excursion_count = df["IsExcursion"].sum()
critical_excursion_count = (df["ExcursionMagnitude"] > risk_logic.CRITICAL_EXCURSION_THRESHOLD).sum()

col1.metric("Total Shipments", total_shipments)
col2.metric("High-Risk Shipments", high_risk_count)
col3.metric("Temp-Excursion Shipments", excursion_count)
col4.metric("Critical Excursions", critical_excursion_count)

st.divider()

# Top 5 highest-risk shipments
st.subheader("Top 5 Highest-Risk Shipments")
top_5 = df.nlargest(5, "RiskScore")[
    ["ShipmentID", "Origin", "Destination", "ProductType", "RiskScore", "RiskLevel", "IsExcursion"]
].copy()
st.dataframe(top_5, use_container_width=True, hide_index=True)

st.divider()

# Risk distribution chart
st.subheader("Risk Distribution")

# Count shipments by RiskLevel (ordered: Low, Medium, High, Critical)
risk_order = ["Low", "Medium", "High", "Critical"]
risk_counts = df["RiskLevel"].value_counts().reindex(risk_order, fill_value=0)

# Status palette (from dataviz skill)
status_colors = {
    "Low": "#0ca30c",        # good (green)
    "Medium": "#fab219",     # warning (yellow)
    "High": "#ec835a",       # serious (orange)
    "Critical": "#d03b3b"    # critical (red)
}

color_list = [status_colors[level] for level in risk_order]

fig = go.Figure(
    data=[
        go.Bar(
            x=risk_order,
            y=risk_counts.values,
            marker=dict(color=color_list),
            text=risk_counts.values,
            textposition="outside",
            hovertemplate="<b>%{x}</b><br>Count: %{y}<extra></extra>"
        )
    ]
)

fig.update_layout(
    title="Shipments by Risk Level",
    xaxis_title="Risk Level",
    yaxis_title="Number of Shipments",
    plot_bgcolor="#fcfcfb",
    paper_bgcolor="#fcfcfb",
    xaxis=dict(
        tickfont=dict(color="#0b0b0b"),
        showgrid=False,
        zeroline=False
    ),
    yaxis=dict(
        tickfont=dict(color="#0b0b0b"),
        gridcolor="#e1e0d9",
        zeroline=False
    ),
    font=dict(color="#0b0b0b", size=12),
    margin=dict(l=40, r=40, t=40, b=40),
    height=400,
    showlegend=False
)

st.plotly_chart(fig, use_container_width=True)

st.divider()

# AI-style recommendation
st.subheader("AI-Generated Recommendation")
recommendation = risk_logic.generate_recommendation(df)
st.info(recommendation)
st.caption("Generated by deterministic rule-based logic, not a live AI model")

st.divider()

# Full data table in expander
with st.expander("View Full Data"):
    st.dataframe(
        df[[
            "ShipmentID", "Origin", "Destination", "ProductType",
            "MinTemp", "MaxTemp", "TempThresholdMin", "TempThresholdMax",
            "RiskScore", "RiskLevel", "IsExcursion", "ExcursionMagnitude", "ExcursionSeverity"
        ]],
        use_container_width=True,
        hide_index=True
    )
